{% set name = "condax" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condax-{{ version }}.tar.gz
  sha256: 6813f99916c554f09b5b67f1202990322fbb6ea6a102081112cbc1ddc7d2e61a

build:
  noarch: python
  entry_points:
    - condax = condax.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - click
    - requests
    - userpath
    - pyyaml
    - ensureconda
    - typer
    - pydantic >=2
    - pydantic-settings

test:
  imports:
    - condax
  commands:
    - pip check
    - condax --help
    - condax --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mariusvniekerk/condax
  doc_url: https://mariusvniekerk.github.io/condax/
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - maresb
    - mariusvniekerk
