{% set name = "condax" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/condax-{{ version }}.tar.gz
  sha256: ff730a2a617756848745784e8c720da8c594b55508d39576c621747321921b5e

build:
  number: 0
  noarch: python
  entry_points:
    - condax = condax.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=0.21.1
    - hatch-vcs
  run:
    - python >=3.7
    - click
    - ensureconda
    - importlib-metadata
    - pydantic
    - pyyaml
    - requests
    - typer
    - userpath

test:
  imports:
    - condax
  commands:
    - pip check
    - condax --help
    - condax --version
  requires:
    - pip

about:
  home: https://github.com/mariusvniekerk/condax
  doc_url: https://mariusvniekerk.github.io/condax/
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - maresb
    - mariusvniekerk
