{% set name = "condax" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/condax-{{ version }}.tar.gz
  sha256: 0b155ae88a5f02ba522372cc2f633cd00e6a9e0520bfa65d897a02c0701f7c35

build:
  number: 0
  noarch: python
  entry_points:
    - condax = condax.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - python >=3.6
    - pyyaml
    - requests
    - userpath

test:
  imports:
    - condax
  commands:
    - pip check
    - condax --help
  requires:
    - pip

about:
  home: https://github.com/mariusvniekerk/condax
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - maresb
    - mariusvniekerk
