{% set name = "condax" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/condax-{{ version }}.tar.gz
  sha256: d80a8a2e0c57328a805bc99aeecb23197cad3008ccd0a2347a399150e877489d

build:
  noarch: python
  entry_points:
    - condax = condax.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=0.21.1
    - hatch-vcs
    - pip
  run:
    - python >=3.7
    - click
    - requests
    - userpath
    - pyyaml
    - ensureconda
    - typer
    - pydantic >=2
    - pydantic-settings
    - importlib-metadata

test:
  imports:
    - condax
  commands:
    - pip check
    - condax --help
    - condax --version
  requires:
    - pip

about:
  home: https://github.com/mariusvniekerk/condax
  doc_url: https://mariusvniekerk.github.io/condax/
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - maresb
    - mariusvniekerk
